-- PointBridge community post comments (additive migration)
-- Safety principle: do not alter or drop existing posts schema/policies.

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  content text not null,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_post_comments_post_created
  on public.post_comments (post_id, created_at asc);

create index if not exists idx_post_comments_user_created
  on public.post_comments (user_id, created_at desc);

create index if not exists idx_post_comments_not_deleted
  on public.post_comments (is_deleted);

alter table public.post_comments enable row level security;

drop policy if exists "post_comments_read_visible_post" on public.post_comments;
create policy "post_comments_read_visible_post" on public.post_comments
for select using (
  exists (
    select 1
    from public.posts p
    where p.id = post_comments.post_id
      and p.is_deleted = false
      and (
        p.category <> 'inquiry'
        or p.is_secret = false
        or auth.uid() = p.user_id
      )
  )
);

drop policy if exists "post_comments_write_login_user" on public.post_comments;
create policy "post_comments_write_login_user" on public.post_comments
for insert with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.posts p
    where p.id = post_comments.post_id
      and p.is_deleted = false
      and (
        p.category <> 'inquiry'
        or p.is_secret = false
        or auth.uid() = p.user_id
      )
  )
);

drop policy if exists "post_comments_update_owner" on public.post_comments;
create policy "post_comments_update_owner" on public.post_comments
for update using (auth.uid() = user_id);

create or replace function public.touch_post_comments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_post_comments_touch_updated_at on public.post_comments;
create trigger trg_post_comments_touch_updated_at
before update on public.post_comments
for each row execute function public.touch_post_comments_updated_at();
