-- PointBridge community posts

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  category text not null check (category in ('notice', 'free', 'inquiry')),
  title text not null,
  content text not null,
  is_secret boolean not null default false,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_posts_category_created_at
  on public.posts (category, created_at desc);

create index if not exists idx_posts_user_created_at
  on public.posts (user_id, created_at desc);

create index if not exists idx_posts_not_deleted
  on public.posts (is_deleted);

alter table public.posts enable row level security;

drop policy if exists "posts_read_public_or_owner" on public.posts;
create policy "posts_read_public_or_owner" on public.posts
for select using (
  category <> 'inquiry'
  or is_secret = false
  or auth.uid() = user_id
);

drop policy if exists "posts_write_login_user" on public.posts;
create policy "posts_write_login_user" on public.posts
for insert with check (auth.uid() = user_id);

drop policy if exists "posts_update_owner" on public.posts;
create policy "posts_update_owner" on public.posts
for update using (auth.uid() = user_id);

create or replace function public.touch_posts_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_posts_touch_updated_at on public.posts;
create trigger trg_posts_touch_updated_at
before update on public.posts
for each row execute function public.touch_posts_updated_at();
